name: A workflow.
on: push
jobs:
  build:
    name: Quote action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./action-a
        env:
          MY_NAME: 'Professor Farnsworth'
